#
# Blog Settings
#
author: Garth Vander Houwen
description: This is Garth's Github
url: https://garthvh.com/
name: Garth's Github
title: Garth's Github
subtitle:

# Github repositories
github_user: garthvh
github_repo_url: https://github.com/garthvh/garthvh.github.io/

# Twitter
twitter_user: garthvh
twitter_tweet_button: true

# YouTube
youtube_channel: http://www.youtube.com/channel/UCI6UGZtVOmfsHNFmHK4tI-Q

# Google Analytics
google_analytics_tracking_id: UA-60861232-1

# Disqus Comments
disqus_short_name: garthvh
disqus_show_comment_count: true

# Uncomment if you are planning to run the blog in a subdirectory
# Note - if you enable this, and attempt to view your site locally you have to use the baseurl in your local path.
# Example, you must use http://localhost:4000/path/to/blog
#baseurl: /path/to/blog
baseurl:

#
# Jekyll Settings
#
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
  parse_block_html: true
category_dir: categories
permalink: pretty
gems: [jekyll-paginate]
paginate: 3
paginate_path: "page/:num"


# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]
