#
# Blog Settings
#
author: Garth Vander Houwen
description: Garth's Website about 3D Printing and code
url: https://garthvh.com
name: Garth's Website
title: Garth's Website
subtitle:

# Github repositories
github_user: garthvh
github_repo_url: https://github.com/garthvh/garthvh.github.io/
repository: garthvh/garthvh.github.io

# Twitter
twitter_user: garthvh
twitter_tweet_button: true

# YouTube
youtube_channel: http://www.youtube.com/channel/UCI6UGZtVOmfsHNFmHK4tI-Q

# Google Analytics
google_analytics_tracking_id: UA-60861232-1

# Uncomment if you are planning to run the blog in a subdirectory
# Note - if you enable this, and attempt to view your site locally you have to use the baseurl in your local path.
# Example, you must use http://localhost:4000/path/to/blog

#
# Jekyll Settings
#
kramdown:
  input: GFM
  syntax_highlighter: rouge

gems: [jekyll-paginate, jekyll-sitemap, jekyll-github-metadata]
category_dir: categories
paginate: 3
paginate_path: "page/:num"
permalink: /:categories/:year/:month/:day/:title/

# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]
