#
# Blog Settings
#
author: Garth Vander Houwen
description: This is Garth's Github
url: http://garthvh.com/
name: Garth's Github
title: Garth's Github
subtitle:

# Github repositories
github_user: garthvh
github_repo_url: https://github.com/GarthVH/garthvh.github.io/

# Twitter
twitter_user: garthvh
twitter_tweet_button: true


# The directory for category index pages. Change it to something else if
# for example you want links like /categories/category1 instead of /category1


# Uncomment if you are planning to run the blog in a subdirectory
# Note - if you enable this, and attempt to view your site locally you have to use the baseurl in your local path.
# Example, you must use http://localhost:4000/path/to/blog
#baseurl: /path/to/blog
baseurl:

#
# Jekyll Settings
#
markdown: redcarpet
redcarpet:
  extensions: ["tables"]
category_dir: categories
permalink: pretty
paginate: 20
paginate_path: "page/:num"


# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]
