- name: Thingiverse
  url: http://www.thingiverse.com/garthvh/about
  img: thingiverse

- name: 3D Hubs
  url: https://www.3dhubs.com/seattle/hubs/garth
  img: 3dhubs

- name: YouTube
  url: http://www.youtube.com/channel/UCI6UGZtVOmfsHNFmHK4tI-Q
  img: youtube
