- name: Thingiverse
  url: http://www.thingiverse.com/garthvh/about
  expo_url: http://www.thingiverse.com/garthvh/about
  img: thingiverse

- name: Vogue
  url: http://www.vogue.com
  expo_url: http://expo.getbootstrap.com/2014/09/30/vogue/
  img: vogue

- name: Riot Design
  url: http://riotdesign.eu/en/
  expo_url: http://expo.getbootstrap.com/2014/03/13/riot-design/
  img: riot

- name: Newsweek
  url: http://www.newsweek.com/
  expo_url: http://expo.getbootstrap.com/2014/02/12/newsweek/
  img: newsweek
